services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db/
    

  valkey:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - valkey_data:/usr/local/etc/valkey

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - uploads_data:/mnt/uploads

  worker:
    command:
      ["/bin/sh", "-c", "rq worker --with-scheduler --url redis://valkey:6379"]
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8001:8001"
    volumes:
      - uploads_data:/mnt/uploads

volumes:
  mongodb_data:
  valkey_data:
  uploads_data: