import os
from dotenv import load_dotenv
import resend

load_dotenv()

def send_resume_analysis_email(recipient_email: str, analysis_result: str, job_role: str):
    """
    Send an email with the resume analysis results.
    
    Args:
        recipient_email: The email address to send the results to
        analysis_result: The analysis text generated by the AI
        job_role: The job role the user applied for
    
    Returns:
        dict: The response from the email API
    """
    try:
        resend_api_key = os.getenv("RESEND_API_KEY")
        if not resend_api_key:
            print("Error: RESEND_API_KEY environment variable not set")
            return {"error": "Email configuration missing"}
        
        # Set API key globally
        resend.api_key = resend_api_key
        
        # Format email content
        formatted_html = f"""
        <html>
            <head>
                <style>
                    body {{
                        font-family: Arial, sans-serif;
                        line-height: 1.6;
                        color: #333;
                        max-width: 800px;
                        margin: 0 auto;
                        padding: 20px;
                    }}
                    h1, h2 {{
                        color: #2c3e50;
                    }}
                    .highlight {{
                        background-color: #f8f9fa;
                        padding: 15px;
                        border-left: 4px solid #4285f4;
                        margin-bottom: 20px;
                    }}
                    .footer {{
                        margin-top: 30px;
                        padding-top: 20px;
                        border-top: 1px solid #eee;
                        font-size: 12px;
                        color: #777;
                    }}
                </style>
            </head>
            <body>
                <h1>Resume Analysis Report</h1>
                <div class="highlight">
                    <h2>Job Role: {job_role}</h2>
                </div>
                <div>
                    {analysis_result.replace("\\n", "<br>").replace("**", "<b>").replace("*", "<i>")}
                </div>
                <div class="footer">
                    This is an automated email. Please do not reply to this message.
                </div>
            </body>
        </html>
        """
        
        # Send email using correct Resend API structure
        params = {
            "from": "Resume Analysis <no-replay@lnbg.in>",
            "to": recipient_email,
            "subject": f"Resume Analysis for {job_role} Position",
            "html": formatted_html
        }
        response = resend.Emails.send(params)
        
        return response
    except Exception as e:
        print(f"Error sending email: {e}")
        return {"error": str(e)}
